version: 0.2

proxy:
  logs: yes

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip3.9 install --target ./package pip install requests-aws4auth opensearch-py 
      - cd package
      - zip -r ../LF1_deployment.zip .
      - cd ..
      - rm -r package
      - pip3.9 install --target ./package pip install requests-aws4auth opensearch-py inflection
      - cd package
      - zip -r ../LF2_deployment.zip .
      - cd ..
      - mv LF1.py lambda_function.py
      - zip LF1_deployment.zip lambda_function.py
      - mv lambda_function.py LF1.py
      - mv LF2.py lambda_function.py
      - zip LF2_deployment.zip lambda_function.py
      - mv lambda_function.py LF2.py
      - mv buildspec.yml buildspec_orig.yml
      - mv deploy.yml buildspec.yml

artifacts:
  files:
    - LF1_deployment.zip
    - LF2_deployment.zip
    - buildspec.yml
  name: lambdas
